### ISSUE TITLE
cuda版本问题

### ISSUE THREAD

**Issue by zzhhzz666** [taugeren/PointOBB-v2#11]
作者大大您好！我想咨询下，我曾经复现过pointobb，然后现在复现v2，我按照您的readme一步一步下载环境，其中conda create -n pointobbpro python=3.7 pytorch==1.7.0 cudatoolkit=10.1 torchvision -c pytorch -y，指定了cudatoolkit版本为10.1，会自动下载同版本的cuda，但是在运行cpm的时候会报cuda的错误，说cuda版本与我的服务器3090显卡不适配，我服务器自带的有几个版本的cuda，但是一安装cudatoolkit就会自动指定下载同版本的cuda，我想问下，我能使用pointobb的cuda版本吗，或者是否有其他更好的方法？祝好！

**Comment by taugeren** [comment]
你好，感谢关注我们的工作。我这里使用的mmrotate版本是mmrotate0.3，然后我运行了conda list，运行的结果如下
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://repo.anaconda.com/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://repo.anaconda.com/pkgs/main
addict                    2.4.0                    pypi_0    pypi
aniso8601                 9.0.1                    pypi_0    pypi
ansi2html                 1.8.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blessed                   1.20.0                   pypi_0    pypi
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.33                  pypi_0    pypi
debugpy                   1.5.1            py39h295c915_0    https://repo.anaconda.com/pkgs/main
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.9                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
e2cnn                     0.2.3                    pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
faiss-gpu                 1.7.2                    pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
flask                     2.2.3                    pypi_0    pypi
flask-restful             0.3.9                    pypi_0    pypi
fonttools                 4.39.0                   pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gpustat                   1.0.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
ipykernel                 6.15.0             pyh210e3f2_0    conda-forge
ipython                   8.12.0             pyh41d4057_0    conda-forge
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2                    pypi_0    pypi
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py39hf3d152e_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    https://repo.anaconda.com/pkgs/main
libffi                    3.3                  he6710b0_2    https://repo.anaconda.com/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/main
libgomp                   11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/main
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/main
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2                    pypi_0    pypi
mmcv-full                 1.5.3                    pypi_0    pypi
mmdet                     2.25.0                   pypi_0    pypi
mmrotate                  0.3.2                     dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://repo.anaconda.com/pkgs/main
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
numpy                     1.23.1                   pypi_0    pypi
nvgpu                     0.10.0                   pypi_0    pypi
nvidia-ml-py              11.495.46                pypi_0    pypi
opencv-contrib-python     4.10.0.84                pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openmim                   0.3.6                    pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0    https://repo.anaconda.com/pkgs/main
ordered-set               4.1.0                    pypi_0    pypi
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1           py39h06a4308_0    https://repo.anaconda.com/pkgs/main
platformdirs              4.3.6                    pypi_0    pypi
prettytable               3.11.0                   pypi_0    pypi
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
protobuf                  4.22.1                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycocotools               2.0.6                    pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pynvml                    11.5.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.9.12               h12debd9_1    https://repo.anaconda.com/pkgs/main
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.7.1                 pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     19.0.2           py39hb69f2a1_2    conda-forge
readline                  8.2                  h5eee18b_0    https://repo.anaconda.com/pkgs/main
requests                  2.28.2                   pypi_0    pypi
rich                      13.3.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.0                   pypi_0    pypi
sentry-sdk                1.17.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.6.3           py39h06a4308_0    https://repo.anaconda.com/pkgs/main
shapely                   2.0.1                    pypi_0    pypi
simplejson                3.19.3                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.41.1               h5eee18b_0    https://repo.anaconda.com/pkgs/main
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sympy                     1.11.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    https://repo.anaconda.com/pkgs/main
torch                     1.10.0+cu113             pypi_0    pypi
torchaudio                0.10.0+cu113             pypi_0    pypi
torchvision               0.11.1+cu113             pypi_0    pypi
tornado                   6.1              py39hb9d737c_3    conda-forge
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h04d1e81_0    https://repo.anaconda.com/pkgs/main
urllib3                   1.26.15                  pypi_0    pypi
virtualenv                20.26.6                  pypi_0    pypi
wandb                     0.14.0                   pypi_0    pypi
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0    https://repo.anaconda.com/pkgs/main
xz                        5.2.10               h5eee18b_1    https://repo.anaconda.com/pkgs/main
yapf                      0.32.0                   pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    https://repo.anaconda.com/pkgs/main

**Comment by zzhhzz666** [comment]
好的！感谢！readme安装pytorch1.7有点太老了，cuda也一直不适配，现在搞好了，谢谢佬，祝身体安康
