### ISSUE TITLE
readme问题

### ISSUE THREAD

**Issue by g973839433** [taugeren/PointOBB-v2#4]
readme中的data_preparetion无法点开，显示没有部署链接，作者大大可以提供给一下数据准备的链接么

**Comment by g973839433** [comment]
DOTA数据集中的点标签是怎么获得的呢，我看配置文件中的标签路径还是旋转框的的路径

**Comment by yangxue0827** [comment]
> readme中的data_preparetion无法点开，显示没有部署链接，作者大大可以提供给一下数据准备的链接么

应该是https://github.com/taugeren/PointOBB-v2/tree/master/tools/data

**Comment by yangxue0827** [comment]
> DOTA数据集中的点标签是怎么获得的呢，我看配置文件中的标签路径还是旋转框的的路径

会在dataloader中处理成点标注

**Comment by taugeren** [comment]
> DOTA数据集中的点标签是怎么获得的呢，我看配置文件中的标签路径还是旋转框的的路径

dataloader加载的gt信息中，进入模型中是[x, y, w, h, a]，我们只用了[x, y]

**Comment by g973839433** [comment]
> > DOTA数据集中的点标签是怎么获得的呢，我看配置文件中的标签路径还是旋转框的的路径
> 
> 会在dataloader中处理成点标注

非常感谢杨大佬，祝好

**Comment by g973839433** [comment]
> > DOTA数据集中的点标签是怎么获得的呢，我看配置文件中的标签路径还是旋转框的的路径
> 
> dataloader加载的gt信息中，进入模型中是[x, y, w, h, a]，我们只用了[x, y]

感谢作者大大，祝好。
