### ISSUE TITLE
关于work_cpm的一些小问题

### ISSUE THREAD

**Issue by ZhenboZhao77** [taugeren/PointOBB-v2#6]
您好作者！
再次打扰，生成work_cpm代码有些疑惑。请问：
在运行 train_cpm_dotav10.py  可视化cpm 后
生成的 work_cpm/visualize/0...38200 这些图片是什么顺序？
为什么我在两次运行代码。对比发现同一个文件夹下的图片不是同一个！

**Comment by ZhenboZhao77** [comment]
我看代码好像是每隔200次迭代可视化一次，但是为什么每次运行代码可视化的图片不一样。

**Comment by taugeren** [comment]
这可能
1. 每次seed不一样
2. 因为你是多卡训练，每次会随机一张卡上的图输出

**Comment by ZhenboZhao77** [comment]
好的，感谢回复。

**Comment by taugeren** [comment]
不客气
