### ISSUE TITLE
How to train my own dataset with the same format as the DOTA dataset?

### ISSUE THREAD

**Issue by yaosx616** [taugeren/PointOBB-v2#9]
I want to train my dataset according to the DOTA dataset format, but my dataset category is different from the DOTA dataset. How can I modify the category?

**Comment by taugeren** [comment]
You can modified "classes" in config file. Moreover, you need to ensure your datasets annotation is as the same format with the DOTA (each line of annotation is x1 y1 x2 y2 x3 y3 x4 y4 cls_name difficulty)

**Comment by yaosx616** [comment]
> You can modified "classes" in config file. Moreover, you need to ensure your datasets annotation is as the same format with the DOTA (each line of annotation is x1 y1 x2 y2 x3 y3 x4 y4 cls_name difficulty)

![image](https://github.com/user-attachments/assets/0bcf411a-0937-474c-aeb2-1b4af185b9b3)
Traceback (most recent call last):
  File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/data2/shuxuan/PointOBB-v2/mmrotate/datasets/dota.py", line 56, in __init__
    super(DOTADataset, self).__init__(ann_file, pipeline, **kwargs)
  File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 80, in __init__
    self.CLASSES = self.get_classes(classes)
  File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 282, in get_classes
    class_names = mmcv.list_from_file(classes)
  File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/fileio/parse.py", line 46, in list_from_file
    with StringIO(file_client.get_text(filename, encoding)) as f:
  File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 1030, in get_text
    return self.client.get_text(filepath, encoding)
  File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 555, in get_text
    with open(filepath, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'reflector'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main()
  File "tools/train.py", line 170, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/data2/shuxuan/PointOBB-v2/mmrotate/datasets/builder.py", line 49, in build_dataset
    dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args)
  File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'reflector'
Hello, I modified the category, but I reported an error. I don't know if you know why？

**Comment by yaosx616** [comment]
> You can modified "classes" in config file. Moreover, you need to ensure your datasets annotation is as the same format with the DOTA (each line of annotation is x1 y1 x2 y2 x3 y3 x4 y4 cls_name difficulty)

![image](https://github.com/user-attachments/assets/9cfc22de-16cf-4e1e-8ae5-fda9943ed13c)
In addition, I would like to ask why the value of loss_bbox is always 0 during training?

**Comment by taugeren** [comment]
> > You can modified "classes" in config file. Moreover, you need to ensure your datasets annotation is as the same format with the DOTA (each line of annotation is x1 y1 x2 y2 x3 y3 x4 y4 cls_name difficulty)
> 
> ![image](https://private-user-images.githubusercontent.com/142800903/388830071-0bcf411a-0937-474c-aeb2-1b4af185b9b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzIyMTIsIm5iZiI6MTczMjUzMTkxMiwicGF0aCI6Ii8xNDI4MDA5MDMvMzg4ODMwMDcxLTBiY2Y0MTFhLTA5MzctNDc0Yy1hZWIyLTFiNGFmMTg1YjliMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxMDUxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTk0N2IzYTlmNGIwN2UwMTc5ZDc5MGU0Njg3NWM4OGI0NDU0MjBmZDFmYjM1N2YyNTZjMTkyOWExZTQyMzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XlOSfIzq2Ho_cqodWgcyCf7sNIVL2hoTzLxN6LoFYxA) Traceback (most recent call last): File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/data2/shuxuan/PointOBB-v2/mmrotate/datasets/dota.py", line 56, in **init** super(DOTADataset, self).**init**(ann_file, pipeline, **kwargs) File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 80, in **init** self.CLASSES = self.get_classes(classes) File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 282, in get_classes class_names = mmcv.list_from_file(classes) File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/fileio/parse.py", line 46, in list_from_file with StringIO(file_client.get_text(filename, encoding)) as f: File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 1030, in get_text return self.client.get_text(filepath, encoding) File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 555, in get_text with open(filepath, encoding=encoding) as f: FileNotFoundError: [Errno 2] No such file or directory: 'reflector'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "tools/train.py", line 195, in main() File "tools/train.py", line 170, in main datasets = [build_dataset(cfg.data.train)] File "/data2/shuxuan/PointOBB-v2/mmrotate/datasets/builder.py", line 49, in build_dataset dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args) File "/data2/shuxuan_anaconda/envs/pointobbv2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') FileNotFoundError: DOTADataset: [Errno 2] No such file or directory: 'reflector' Hello, I modified the category, but I reported an error. I don't know if you know why？

You can change CLASSES in config file, such as file in ./config/pointobbv2/train_cpm.py.

**Comment by taugeren** [comment]
> > You can modified "classes" in config file. Moreover, you need to ensure your datasets annotation is as the same format with the DOTA (each line of annotation is x1 y1 x2 y2 x3 y3 x4 y4 cls_name difficulty)
> 
> ![image](https://private-user-images.githubusercontent.com/142800903/388832300-9cfc22de-16cf-4e1e-8ae5-fda9943ed13c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzIyMTIsIm5iZiI6MTczMjUzMTkxMiwicGF0aCI6Ii8xNDI4MDA5MDMvMzg4ODMyMzAwLTljZmMyMmRlLTE2Y2YtNGUxZS04YWU1LWZkYTk5NDNlZDEzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxMDUxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2MwN2Y0ZGZkZTQ3Nzc4Mzk0ZDE1Yzg5YTEzYjgzNmI1M2ZlMDhkZmM2OWEzYmI4MzIzMzEzM2I1MDUwZGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S4-KaNr4lHlxAQCQ348FPvZJU-bBitPeHIaoBJU8ZZ8) In addition, I would like to ask why the value of loss_bbox is always 0 during training?

It is normal. We only have point label, then we don't have the regression loss.

**Comment by yaosx616** [comment]
> > > You can modified "classes" in config file. Moreover, you need to ensure your datasets annotation is as the same format with the DOTA (each line of annotation is x1 y1 x2 y2 x3 y3 x4 y4 cls_name difficulty)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/142800903/388832300-9cfc22de-16cf-4e1e-8ae5-fda9943ed13c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzIyMTIsIm5iZiI6MTczMjUzMTkxMiwicGF0aCI6Ii8xNDI4MDA5MDMvMzg4ODMyMzAwLTljZmMyMmRlLTE2Y2YtNGUxZS04YWU1LWZkYTk5NDNlZDEzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxMDUxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2MwN2Y0ZGZkZTQ3Nzc4Mzk0ZDE1Yzg5YTEzYjgzNmI1M2ZlMDhkZmM2OWEzYmI4MzIzMzEzM2I1MDUwZGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S4-KaNr4lHlxAQCQ348FPvZJU-bBitPeHIaoBJU8ZZ8) In addition, I would like to ask why the value of loss_bbox is always 0 during training?
> 
> It is normal. We only have point label, then we don't have the regression loss.

Thank you for your answer!
